name: wimax_pentest
description: Advanced Android Penetration Testing Tool for Network Security Assessment
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  permission_handler: ^11.0.1
  connectivity_plus: ^5.0.1
  path_provider: ^2.1.1
  http: ^1.1.0
  file_picker: ^6.1.1
  shared_preferences: ^2.2.2
  flutter_local_notifications: ^16.1.0
  device_info_plus: ^9.1.0
  network_info_plus: ^4.1.0
  process_run: ^0.12.5+2
  csv: ^5.0.2
  intl: ^0.18.1
  flutter_staggered_grid_view: ^0.7.0
  animated_text_kit: ^4.2.2
  lottie: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/animations/
    - assets/wordlists/
    - assets/tools/